test

diff --git a/.github/workflows/playwright-e2e.yml b/.github/workflows/playwright-e2e.yml
--- a/.github/workflows/playwright-e2e.yml
+++ b/.github/workflows/playwright-e2e.yml
@@ -25,8 +25,10 @@ jobs:
         npm config set @navikt:registry https://npm.pkg.github.com
         npm config set //npm.pkg.github.com/:_authToken $NPM_AUTH_TOKEN
         npm ci --prefer-offline --no-audit --ignore-scripts
+    - name: Clone pam-docker-compose-shared
+      run: git clone git@github.com:navikt/pam-docker-compose-shared.git ../pam-docker-compose-shared || true
     - name: Build application
-      run: npm run build:no-sourcemap
+      run: npm run build:no-sourcemap || (echo "Build failed" && exit 1)
     - name: Run application
       env:
         NODE_ENV: production
